# steps:
#   # Step 1: Install dependencies (Node.js and Firebase CLI)
#   # - name: 'gcr.io/cloud-builders/npm'
#   #   args: ['install']

#   # Step 2: Build the Next.js application
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['run', 'build']

#   # Step 3: Deploy to Firebase Hosting
#   - name: 'gcr.io/ee-jiffybook-preprod/firebase'
#     args: ['deploy', '--only', 'hosting']

# # Use the following substitutions if needed
# substitutions:
#   _FIREBASE_TOKEN: "1//0gApRyENNAB-NCgYIARAAGBASNwF-L9IrLApQo1yhz5EFoZZ2YGfdhNOpAm4CBiF7LhGEXhVCGQFIJTmq--OIOyF_geFQOAAob8g"
#   _FIREBASE_PROJECT_ID: jiffybook-preprod
#   _FIREBASE_PROJECT_NAME: "JiffyBook Estonia Preprod"




# steps:
#   # Step 1: Install dependencies (Node.js and Firebase CLI)
#   # - name: 'gcr.io/cloud-builders/npm'
#   #   args: ['install', '-g', 'firebase-tools']

#   # Step 2: Authenticate with Firebase (if needed)
#   # You can use environment variables for authentication if required.

#   # Step 3: Build the Next.js application or any other necessary build steps
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['run', 'build']  # Replace with your build command

#   # Step 4: Configure Firebase to use the correct project
#   - name: 'gcr.io/cloud-builders/firebase'
#     args: ['use', 'ee-jiffybook-preprod']

#   # Step 5: Deploy to Firebase Hosting
#   - name: 'gcr.io/cloud-builders/firebase'
#     args: ['deploy', '--only', 'hosting']  # Deploy only the hosting part

# # Use the following substitutions if needed
# substitutions:
#   _FIREBASE_TOKEN: "1//0gApRyENNAB-NCgYIARAAGBASNwF-L9IrLApQo1yhz5EFoZZ2YGfdhNOpAm4CBiF7LhGEXhVCGQFIJTmq--OIOyF_geFQOAAob8g"





steps:
  # Step 1: Install dependencies (Node.js and Firebase CLI)
  # - name: 'node:14'  # Use a Node.js runtime
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - 'npm install -g firebase-tools'

  # Step 2: Authenticate with Firebase (if needed)
  # You can use environment variables for authentication if required.

  # Step 3: Build the Next.js application or any other necessary build steps
  - name: 'node:14'  # Use a Node.js runtime
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm run build'  # Replace with your build command

  # Step 4: Configure Firebase to use the correct project
  - name: 'node:14'  # Use a Node.js runtime
    entrypoint: 'bash'
    args:
      - '-c'
      - 'firebase use ee-jiffybook-preprod'  # Replace with your Firebase project alias or project ID

  # Step 5: Deploy to Firebase Hosting
  - name: 'node:14'  # Use a Node.js runtime
    entrypoint: 'bash'
    args:
      - '-c'
      - 'firebase deploy --only hosting'  # Deploy only the hosting part

# Use the following substitutions if needed
substitutions:
  _FIREBASE_TOKEN: "1//0gApRyENNAB-NCgYIARAAGBASNwF-L9IrLApQo1yhz5EFoZZ2YGfdhNOpAm4CBiF7LhGEXhVCGQFIJTmq--OIOyF_geFQOAAob8g"


