steps:
  # Step 1: Install dependencies (Node.js and Firebase CLI)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the Next.js application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy to Firebase Hosting
  - name: 'gcr.io/jiffybook-preprod/firebase'
    args: ['deploy', '--only', 'hosting']

# Use the following substitutions if needed
substitutions:
_FIREBASE_TOKEN: "1//0gApRyENNAB-NCgYIARAAGBASNwF-L9IrLApQo1yhz5EFoZZ2YGfdhNOpAm4CBiF7LhGEXhVCGQFIJTmq--OIOyF_geFQOAAob8g"
  _FIREBASE_PROJECT_ID: jiffybook-preprod
  _FIREBASE_PROJECT_NAME: JiffyBook-preprod