steps:
  # Step 1: Install dependencies (Node.js and Firebase CLI)
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['install']

  # Step 2: Build the Next.js application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy to Firebase Hosting
  - name: 'gcr.io/ee-jiffybook-preprod/firebase'
    args: ['deploy', '--only', 'hosting']

# Use the following substitutions if needed
substitutions:
  _FIREBASE_TOKEN: "1//0gApRyENNAB-NCgYIARAAGBASNwF-L9IrLApQo1yhz5EFoZZ2YGfdhNOpAm4CBiF7LhGEXhVCGQFIJTmq--OIOyF_geFQOAAob8g"
  _FIREBASE_PROJECT_ID: jiffybook-preprod
  _FIREBASE_PROJECT_NAME: "JiffyBook Estonia Preprod"




gcloud projects add-iam-policy-binding 538384824023 \
  --member=serviceAccount:jiffybook-preprod@appspot.gserviceaccount.com  \
  --role=roles/storage.objectViewer

gcloud projects add-iam-policy-binding 538384824023 \
  --member=serviceAccount:jiffybook-preprod@appspot.gserviceaccount.com \
  --role=roles/container.developer



  gcloud iam service-accounts keys create KEY_FILE.json \
  --iam-account=jiffybook-preprod@appspot.gserviceaccount.com
 gcloud auth activate-service-account --key-file=KEY_FILE.json

